### ISSUE TITLE
Marque "blanche"

### ISSUE THREAD

**Issue by antdlt** [isignif/vue-app#17]
Tout doit être customisable (couleurs, logo, etc).

**Comment by madeindjs** [comment]
L'idée c'est:

- de faire comme bootstrap et de faire un fichier `variable.scss` avec toutes les variables à modifier commes les couleures primaires
- de mettre toutes les images spécifiques à isignif (logo, favicon, etc..) dans `src/assets/brand`

**Comment by madeindjs** [comment]
Fait dans #19
